---
- name: "Add jump users group exists {{ jump_host_user_name }}"
  ansible.builtin.group:
    name: "{{ jump_host_user_name }}"
    state: present
  become: true
  become_user: root

- name: "Add jump user {{ jump_host_user_name }}"
  ansible.builtin.user:
    name: "{{ jump_host_user_name }}"
    comment: "{{ jump_host_user_comment }}"
    group: "{{ jump_host_user_name }}"
    groups: "{{ jump_host_user_groups }}"
    createhome: true
  become: true
  become_user: root

- name: Get home directory of jump host user
  ansible.builtin.getent:
    database: passwd
    key: "{{ jump_host_user_name }}"

- name: Set home directory var for jump host user
  ansible.builtin.set_fact:
    jump_host_user_home: "{{ getent_passwd[jump_host_user_name][4] }}"

- name: Ensure .ssh exists and is secure
  ansible.builtin.file:
    path: "{{ jump_host_user_home }}/.ssh"
    state: directory
    owner: "{{ jump_host_user_name }}"
    group: "{{ jump_host_user_name }}"
    mode: '0700'
  become: true
  become_user: root

- name: Ensure .ssh/controlmasters exists and is secure
  ansible.builtin.file:
    path: "{{ jump_host_user_home }}/.ssh/controlmasters"
    state: directory
    owner: "{{ jump_host_user_name }}"
    group: "{{ jump_host_user_name }}"
    mode: '0700'
  become: true
  become_user: root

- name: Deploy SSH key to clone ansible repo
  ansible.builtin.copy:
    content: "{{ jump_host_git_clone_private_key }}"
    dest: "{{ jump_host_user_home }}/.ssh/ansible_jump_host_git_clone_private_key"
    owner: "{{ jump_host_user_name }}"
    group: "{{ jump_host_user_name }}"
    mode: "0600"
  become: true
  become_user: root

- name: Ensure ansible repo # noqa latest[git]
  ansible.builtin.git:
    repo: "{{ jump_host_ansible_repo }}"
    dest: "{{ jump_host_user_home }}/ansible"
    key_file: "{{ jump_host_user_home }}/.ssh/ansible_jump_host_git_clone_private_key"
    accept_hostkey: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ jump_host_user_name }}"

- name: Ensure jumphost specifig packages
  ansible.builtin.package:
    name:
      - tmux
      - python3-full
      - python3-virtualenv
      - dnsutils
      - pwgen
      - nmap
      - xclip
      # - fonts-powerline
    state: present
  become: true
  become_user: root

# Powerline seems to be broken since it requires e "python" executable and not python3?
# Is this project even alive?
# - name: Install powerline-status
#   ansible.builtin.pip:
#     name:
#       - powerline-status
#       - powerline-gitstatus
#     virtualenv: "/home/{{ jump_host_user_name }}/.local"
#   become: true
#   become_user: "{{ jump_host_user_name }}"

- name: "Configure port 22 for sshd"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "Port 22"
    line: "Port 22"
  notify: Restart sshd
  become: true
  become_user: root

- name: "Configure additional sshd port {{ jump_host_ssh_port }}"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port {{ jump_host_ssh_port }}"
    line: "Port {{ jump_host_ssh_port }}"
    insertafter: "^Port 22"
  notify: Restart sshd
  become: true
  become_user: root

# TODO
# * As user oxi after sync: python .nextrsync/Settings/Linux/setup.py
